//! The effect palette's rows: what each kind of effect brings.
//!
//! GENERATED-FROM-TEMPLATES NOTE: ids below are *templates* (`chorus.mix`).
//! `crate::fx` turns them into instance rows (`fx.3.chorus.mix`).

use crate::params::{ParamDef, Taper, Unit};

pub(crate) const DRIVE_ROWS: &[ParamDef] = &[
    // Drive: shape the material with a curve, then a tone filter. Put it before
    // a crusher or a ring modulator and they get the harmonics it added. Type
    // names come from `DriveType::NAMES`.
    ParamDef {
        id: "drive.on",
        name: "Drive",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "drive.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "drive.amount",
        name: "Amount",
        min: 0.0,
        max: 48.0,
        default: 24.0,
        taper: Taper::Linear,
        unit: Unit::None,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "drive.tone",
        name: "Tone",
        min: 200.0,
        max: 20_000.0,
        default: 8_000.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "drive.type",
        name: "Type",
        min: 0.0,
        max: 3.0,
        default: 0.0,
        taper: Taper::Stepped(4),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
];

pub(crate) const CRUSH_ROWS: &[ParamDef] = &[
    ParamDef {
        id: "crush.on",
        name: "Crush",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    // Defaults to zero, like the ring modulator: loading a patch and pressing
    // play gives you the material, not an effect you did not ask for.
    ParamDef {
        id: "crush.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "crush.bits",
        name: "Bits",
        min: 1.0,
        max: 16.0,
        default: 16.0,
        // Bits are already the logarithm of the level count, so a linear
        // control here is the perceptually even one.
        taper: Taper::Linear,
        unit: Unit::None,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "crush.rate",
        name: "Rate",
        min: 200.0,
        max: 48_000.0,
        default: 48_000.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
];

pub(crate) const RING_ROWS: &[ParamDef] = &[
    ParamDef {
        id: "ring.on",
        name: "Ring modulation",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "ring.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "ring.freq",
        name: "Frequency",
        min: 1.0,
        max: 5000.0,
        default: 140.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
];

pub(crate) const CHORUS_ROWS: &[ParamDef] = &[
    // The chorus: swept copies of the sound, the right's LFOs between the
    // left's, so it widens as well as thickens. Rate and depth stop where it
    // would turn to warble (`chorus::MAX_RATE_HZ`). EQ is a shelf on the copies
    // only.
    // Type picks the voicing: the plain chorus; a string-ensemble one, wider
    // and lusher; or Choir, copies held sharp and flat for voices, where
    // depth is the detune and rate how fast the copies wander. Names from
    // `ChorusType::NAMES`. In the ensemble, rate is the slow swirl and depth
    // scales it and its fast shimmer together.
    ParamDef {
        id: "chorus.on",
        name: "Chorus",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "chorus.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.5,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "chorus.type",
        name: "Type",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        taper: Taper::Stepped(3),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "chorus.rate",
        name: "Rate",
        min: 0.05,
        max: crate::chorus::MAX_RATE_HZ,
        default: 0.6,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "chorus.depth",
        name: "Depth",
        min: 0.0,
        max: 1.0,
        default: 0.5,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    // Voices is continuous: the next copy fades in as it turns, so it sweeps
    // and follows an LFO without a click. Few beat, many blur into a wall.
    ParamDef {
        id: "chorus.voices",
        name: "Voices",
        min: 1.0,
        max: crate::chorus::MAX_VOICES as f32,
        default: 4.0,
        taper: Taper::Linear,
        unit: Unit::None,
        smooth_ms: 20.0,
    },
    // Spread scales where every voicing's copies sit, half to twice; low cut
    // is a high-pass on the copies. Both shape every voicing alike.
    ParamDef {
        id: "chorus.spread",
        name: "Spread",
        min: crate::chorus::SPREAD_MIN,
        max: crate::chorus::SPREAD_MAX,
        default: 1.0,
        taper: Taper::Exponential,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "chorus.lowcut",
        name: "Low cut",
        min: crate::chorus::LOW_CUT_MIN_HZ,
        max: crate::chorus::LOW_CUT_MAX_HZ,
        default: 240.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "chorus.eq",
        name: "EQ",
        min: -crate::chorus::EQ_RANGE_DB,
        max: crate::chorus::EQ_RANGE_DB,
        default: 0.0,
        taper: Taper::Bipolar,
        unit: Unit::Db,
        smooth_ms: 20.0,
    },
];

pub(crate) const OVERTONE_ROWS: &[ParamDef] = &[
    // Overtone: layers made from the incoming sound, an octave down, an octave up and a fifth up, each with its own level. An effect on the sound, not a synth.
    // First of the modulators, so the chorus and everything after thicken the layers too.
    ParamDef {
        id: "overtone.on",
        name: "Overtone",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "overtone.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.5,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "overtone.sub",
        name: "Sub",
        min: 0.0,
        max: 1.0,
        default: 0.5,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "overtone.octave",
        name: "Octave",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "overtone.fifth",
        name: "Fifth",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "overtone.tone",
        name: "Tone",
        min: crate::overtone::TONE_MIN_HZ,
        max: crate::overtone::TONE_MAX_HZ,
        default: 5000.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
];

pub(crate) const FLANGER_ROWS: &[ParamDef] = &[
    // The flanger: a very short swept delay summed with the dry, so comb notches sweep the spectrum. Feedback is bipolar: negative is the hollow comb, positive the ringing one.
    ParamDef {
        id: "flanger.on",
        name: "Flanger",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "flanger.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.5,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "flanger.manual",
        name: "Manual",
        min: crate::flanger::MANUAL_MIN_MS,
        max: crate::flanger::MANUAL_MAX_MS,
        default: 1.5,
        taper: Taper::Exponential,
        unit: Unit::Ms,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "flanger.rate",
        name: "Rate",
        min: crate::flanger::MIN_RATE_HZ,
        max: crate::flanger::MAX_RATE_HZ,
        default: 0.25,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "flanger.depth",
        name: "Depth",
        min: 0.0,
        max: 1.0,
        default: 0.7,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "flanger.feedback",
        name: "Feedback",
        min: -crate::flanger::MAX_FEEDBACK,
        max: crate::flanger::MAX_FEEDBACK,
        default: 0.5,
        taper: Taper::Bipolar,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
];

pub(crate) const WEAR_ROWS: &[ParamDef] = &[
    // Wear: a cassette that has been looked after badly. Wow and flutter bend the pitch, Unstable lurches it on a chaotic path that never repeats, Dropouts dip the level, and Dull closes a low-pass that follows the level, so quiet parts go muffled.
    ParamDef {
        id: "wear.on",
        name: "Wear",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "wear.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.7,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "wear.wow",
        name: "Wow",
        min: 0.0,
        max: 1.0,
        default: 0.4,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "wear.flutter",
        name: "Flutter",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "wear.unstable",
        name: "Unstable",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "wear.dropouts",
        name: "Dropouts",
        min: 0.0,
        max: 1.0,
        default: 0.2,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "wear.dull",
        name: "Dull",
        min: 0.0,
        max: 1.0,
        default: 0.4,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
];

pub(crate) const DELAY_ROWS: &[ParamDef] = &[
    // The clean delay: faithful repeats, darkened only by
    // Tone in the loop. Time glides, so turning it bends pitch. Ping-pong
    // sends each repeat to the other side. The degraded one is `echo`.
    ParamDef {
        id: "delay.on",
        name: "Delay",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "delay.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "delay.time",
        name: "Time",
        min: crate::delay::DELAY_MIN_MS,
        max: crate::delay::DELAY_MAX_MS,
        default: 350.0,
        taper: Taper::Exponential,
        unit: Unit::Ms,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "delay.feedback",
        name: "Feedback",
        min: 0.0,
        max: crate::delay::FEEDBACK_MAX,
        default: 0.4,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "delay.tone",
        name: "Tone",
        min: crate::delay::TONE_MIN_HZ,
        max: crate::delay::TONE_MAX_HZ,
        default: 8000.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "delay.pingpong",
        name: "Ping-pong",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
];

pub(crate) const ECHO_ROWS: &[ParamDef] = &[
    // The echo: the degraded counterpart of the delay. Each repeat comes back darker and more saturated, with the pitch wandering a little, like a loop of tape.
    ParamDef {
        id: "echo.on",
        name: "Echo",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "echo.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.35,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "echo.time",
        name: "Time",
        min: crate::echo::ECHO_MIN_MS,
        max: crate::echo::ECHO_MAX_MS,
        default: 300.0,
        taper: Taper::Exponential,
        unit: Unit::Ms,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "echo.feedback",
        name: "Feedback",
        min: 0.0,
        max: crate::echo::MAX_FEEDBACK,
        default: 0.45,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "echo.tone",
        name: "Tone",
        min: crate::echo::TONE_MIN_HZ,
        max: crate::echo::TONE_MAX_HZ,
        default: 3500.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "echo.wobble",
        name: "Wobble",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "echo.grit",
        name: "Grit",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
];

pub(crate) const RISE_ROWS: &[ParamDef] = &[
    // Rise: cascading pitch-shifted repeats. Each repeat arrives Shift semitones above the last, so the trail climbs. Wobble wanders the shift; Tone keeps the climbing repeats from turning to glass.
    ParamDef {
        id: "rise.on",
        name: "Rise",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "rise.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.4,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "rise.time",
        name: "Time",
        min: crate::rise::RISE_MIN_MS,
        max: crate::rise::RISE_MAX_MS,
        default: 380.0,
        taper: Taper::Exponential,
        unit: Unit::Ms,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "rise.feedback",
        name: "Feedback",
        min: 0.0,
        max: crate::rise::MAX_FEEDBACK,
        default: 0.6,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "rise.shift",
        name: "Shift",
        min: -crate::rise::MAX_SHIFT_ST,
        max: crate::rise::MAX_SHIFT_ST,
        default: 7.0,
        taper: Taper::Bipolar,
        unit: Unit::Semitones,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "rise.wobble",
        name: "Wobble",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "rise.tone",
        name: "Tone",
        min: crate::rise::TONE_MIN_HZ,
        max: crate::rise::TONE_MAX_HZ,
        default: 6000.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
];

pub(crate) const REVERB_ROWS: &[ParamDef] = &[
    // The reverb: an eight-line feedback network. Type picks the room, Decay is how long the tail lasts, Size scales the space, Tone is how fast the highs die, Pre-delay gaps it from the dry.
    ParamDef {
        id: "reverb.on",
        name: "Reverb",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        taper: Taper::Stepped(2),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "reverb.mix",
        name: "Mix",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "reverb.type",
        name: "Type",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        taper: Taper::Stepped(3),
        unit: Unit::None,
        smooth_ms: 0.0,
    },
    ParamDef {
        id: "reverb.decay",
        name: "Decay",
        min: crate::reverb::MIN_DECAY_S,
        max: crate::reverb::MAX_DECAY_S,
        default: 2.5,
        taper: Taper::Exponential,
        unit: Unit::Seconds,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "reverb.size",
        name: "Size",
        min: 0.0,
        max: 1.0,
        default: 0.5,
        taper: Taper::Linear,
        unit: Unit::Percent,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "reverb.tone",
        name: "Tone",
        min: crate::reverb::MIN_TONE_HZ,
        max: crate::reverb::MAX_TONE_HZ,
        default: 6000.0,
        taper: Taper::Exponential,
        unit: Unit::Hz,
        smooth_ms: 20.0,
    },
    ParamDef {
        id: "reverb.predelay",
        name: "Pre-delay",
        min: 0.0,
        max: crate::reverb::MAX_PREDELAY_MS,
        default: 12.0,
        taper: Taper::Linear,
        unit: Unit::Ms,
        smooth_ms: 20.0,
    },
];
